config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/JanPremus/fd3d_TSN:
      branch: master
      repo: https://github.com/JanPremus/fd3d_TSN
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/JanPremus/fd3d_TSN git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-chocolate-russel.sh
        container: qc.acc_breezy-wisteria-mammoth
  QC.Doc:
    repos:
      github.com/JanPremus/fd3d_TSN find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-periwinkle-foxhound.sh
        container: qc.doc_hilly-magenta-cichlid
      github.com/JanPremus/fd3d_TSN git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-chestnut-bee.sh
        container: qc.doc_gimpy-persimmon-angora
  QC.Lic:
    repos:
      github.com/JanPremus/fd3d_TSN licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-linen-otter.sh
        container: qc.lic_lumpy-razzmatazz-dane
  QC.Ver:
    repos:
      github.com/JanPremus/fd3d_TSN get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-beige-quail.sh
        container: qc.ver_muzzy-mustard-kangaroo
timeout: 5400
